context:
  version: "0.11.1"

package:
  name: purs-tidy
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/purs-tidy/-/purs-tidy-${{ version }}.tgz
  sha256: f9b5fe367b70670ed86203b592448648b9e95dbf229a03c1d900a3447ea1b281

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - purs-tidy --help

about:
  license: MIT
  license_file: LICENSE
  summary: A syntax tidy-upper (formatter) for PureScript.
  homepage: https://github.com/natefaubion/purescript-tidy
  repository: https://github.com/natefaubion/purescript-tidy

extra:
  recipe-maintainers:
    - danielnachun
